# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PublishBuildArtifacts@1
inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(8fe01723-c68a-4842-b6b6-341e5e14be9f)'
    appType: 'webAppLinux'
    appName: 'dej-mashala'
    deployToSlotOrASE: true
    resourceGroupName: 'mashala'
    slotName: 'dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
  
